# Generated by Django 4.2.9 on 2024-04-02 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(name="HoursOfOperation",),
        migrations.DeleteModel(name="RoomNumber",),
        migrations.AddField(
            model_name="teachingassistant",
            name="hours_of_operation",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="teachingassistant",
            name="room_number",
            field=models.CharField(default="", max_length=10),
        ),
        migrations.AlterField(
            model_name="teachingassistant",
            name="name",
            field=models.CharField(default="", max_length=100),
        ),
    ]
