# Generated by Django 4.2.9 on 2024-04-02 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0002_delete_hoursofoperation_delete_roomnumber_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="teachingassistant",
            name="class_name",
            field=models.CharField(default="", max_length=50),
        ),
    ]
